import './global.css';

export const metadata = {
  title: 'Frontend app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black p-10">{children}</body>
    </html>
  );
}
